#!/system/bin/sh
# uncomment any of them if needed

###########################
# CPU governor            #
# Default: smartassv2     #
###########################
#echo interactive > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo smartassv2 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
#echo conservative > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
#echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

###########################
# CPU frequency           #
# Default: 245 ~ 672      #
# Min freq.:  245         #
# Max freq.: 672          #
###########################
echo 245760 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 672000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

exit 0

